name: Docker Image CI

on:
  push:
    branches: [ Main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t test-server --tag my-image-name:$(date +%s)
    
    - name: Run Docker image
      run: docker run -d -p 3333:3333 -ti test-server -F -p 3333
      
    - name: Check Docker status
      run: docker ps
    
    - name: Terminate Docker image
      run: docker container stop $(docker ps --filter ancestor=test-server --format="{{.Names}}")
